package org.slowcoders.hyperql.sample.hq.bookstore.model;

import org.slowcoders.hyperquery.core.*;
import lombok.Getter;
import lombok.Setter;

/** This source is generated by HQL-JDBC */

public interface bookstore_jpa {


}