
database: postgresql

spring:
  sql.init:
    mode: always
    schema-locations: classpath*:db/${database}/starwars-schema.sql
    data-locations: classpath*:db/${database}/starwars-data.sql
  session:
    store-type: none  # Session 저장 유형 StoreType 참조.
    timeout: 3600     # Session timeout.


  datasource:
    url: ${DB_URL:jdbc:${database}://localhost/hyper_jdbc}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:hyper_jdbc}
    password: ${DB_PASS:hyper_jdbc}

