database: postgres

spring:
  sql.init.mode: always
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost/petclinic}
    username: ${POSTGRES_USER:petclinic}
    password: ${POSTGRES_PASS:petclinic}

spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost/petclinic}
spring.datasource.username=${POSTGRES_USER:petclinic}
spring.datasource.password=${POSTGRES_PASS:petclinic}
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
