version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jql_demo
      POSTGRES_PASSWORD: jql_demo
      POSTGRES_DB: jql_demo
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
