version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jql_demo
      POSTGRES_PASSWORD: jql_demo
      POSTGRES_DB: jql_demo

  mariadb:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: jql_demo
      MYSQL_DATABASE: jql_demo
      MYSQL_USER: jql_demo
      MYSQL_PASSWORD: jql_demo
      TZ: Asia/Seoul

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: jql_demo
      MYSQL_DATABASE: jql_demo
      MYSQL_USER: jql_demo
      MYSQL_PASSWORD: jql_demo
      TZ: Asia/Seoul

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: jql_demo
      KIBANA_PASSWORD: jql_demo

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    ports:
      - 5601:5601
      - 9300:9300
    environment:
      KIBANA_PASSWORD: jql_demo
