version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hyper_jdbc
      POSTGRES_PASSWORD: hyper_jdbc
      POSTGRES_DB: hyper_jdbc

  mariadb:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data/mariadb:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: hyper_jdbc
      MYSQL_USER: hyper_jdbc
      MYSQL_PASSWORD: hyper_jdbc

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: hyper_jdbc
      MYSQL_USER: hyper_jdbc
      MYSQL_PASSWORD: hyper_jdbc

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: hyper_jdbc
      KIBANA_PASSWORD: hyper_jdbc

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    ports:
      - 5601:5601
      - 9300:9300
    environment:
      KIBANA_PASSWORD: hyper_jdbc
