spring:
  config:
    import:
      - develop-config.yaml
# 주의) import 된 파일이 현재 yml 파일보다 적용 우선 순위가 높다!
# section 을 분리하여 이 문제를 해소한다.
---

spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: ${DB_URL:jdbc:log4jdbc:postgresql://localhost/hql_demo}?useSSL=false&allowPublicKeyRetrieval=true
#    username: ${DB_USER:hql_demo}
#    password: ${DB_PASS:hql_demo}
    main:
      hikari:
        jdbcUrl: ${DB_URL:jdbc:log4jdbc:postgresql://localhost/hql_demo}?useSSL=false&allowPublicKeyRetrieval=true
        username: ${DB_USER:hql_demo}
        password: ${DB_PASS:hql_demo}
    replica:
      hikari:
        jdbcUrl: ${DB_URL:jdbc:log4jdbc:postgresql://localhost/hql_demo}?useSSL=false&allowPublicKeyRetrieval=true
        username: ${DB_USER:hql_demo}
        password: ${DB_PASS:hql_demo}



hpss:
  security:
    ksign:
      agent-home: 'C:\Chamomile\workspace\hpss-proj\agent'
      first-port: 9909
      first-ip: 127.0.0.1

